import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma';
import { asyncHandler, ApiError } from '../utils/http';
import { requireAuth } from '../middleware/auth';
import { requireProjectAccess, requireSuperadmin } from '../middleware/rbac';
import { audit } from '../middleware/audit';
import {
  fileUrl,
  removeUploadedFile,
  signFileUrl,
  upload,
  verifyUpload,
} from '../middleware/upload';

const router = Router({ mergeParams: true });
router.use(requireAuth, requireProjectAccess);

router.get(
  '/',
  asyncHandler(async (req, res) => {
    const { type } = z
      .object({
        type: z
          .enum([
            'CONTRACT',
            'APPROVAL',
            'CUSTOMER',
            'RECEIPT',
            'COMPLETION',
            'PHOTO',
            'INVOICE',
            'OTHER',
          ])
          .optional(),
      })
      .parse(req.query);
    const docs = await prisma.document.findMany({
      where: { projectId: req.params.projectId, ...(type && { type }) },
      include: { uploadedBy: { select: { id: true, name: true } } },
      orderBy: { createdAt: 'desc' },
      take: 500,
    });
    res.json(docs.map((d) => ({ ...d, fileUrl: signFileUrl(d.fileUrl) })));
  }),
);

router.post(
  '/',
  upload.single('file'),
  asyncHandler(async (req, res) => {
    if (!req.file) throw ApiError.badRequest('file is required');
    await verifyUpload(req.file);
    const { type, name } = z
      .object({
        type: z.enum([
          'CONTRACT',
          'APPROVAL',
          'CUSTOMER',
          'RECEIPT',
          'COMPLETION',
          'PHOTO',
          'INVOICE',
          'OTHER',
        ]),
        name: z.string().min(1),
      })
      .parse(req.body);
    const doc = await prisma.document.create({
      data: {
        projectId: req.params.projectId,
        type,
        name,
        fileUrl: fileUrl(req.file.filename),
        mimeType: req.file.mimetype,
        sizeBytes: req.file.size,
        uploadedById: req.user!.id,
      },
      include: { uploadedBy: { select: { id: true, name: true } } },
    });
    audit(req, 'document.upload', 'Document', doc.id, { type, name });
    res.status(201).json({ ...doc, fileUrl: signFileUrl(doc.fileUrl) });
  }),
);

router.delete(
  '/:id',
  requireSuperadmin,
  asyncHandler(async (req, res) => {
    const doc = await prisma.document.findUnique({ where: { id: req.params.id } });
    if (!doc || doc.projectId !== req.params.projectId) throw ApiError.notFound();
    // Generated invoices and receipts share their file with the Invoice or
    // Payment row that owns it. Deleting from here would leave a legal
    // document pointing at a missing file, so it has to be done at the source.
    if (doc.systemGenerated) {
      throw ApiError.conflict(
        'This document was generated by the system. Void the invoice or receipt it belongs to instead.',
      );
    }
    await prisma.document.delete({ where: { id: doc.id } });
    removeUploadedFile(doc.fileUrl);
    audit(req, 'document.delete', 'Document', doc.id);
    res.json({ ok: true });
  }),
);

export default router;
